### ISSUE TITLE
Button "Add technology blip" doesnt work

### ISSUE THREAD

**Issue by A9afon** [a5lab/axion#409]
Go to "https://axion.a5lab.com/settings/technology_blips/add".
Click on "Add technology blip".
See 500 error.

**Comment by arufanov** [comment]
@A9afon 
* Could you provide test for this error? 
* here is call stack:

```
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Apr 01 23:56:59 MSK 2023
There was an unexpected error (type=Internal Server Error, status=500).
Request processing failed: org.springframework.dao.InvalidDataAccessApiUsageException: detached entity passed to persist: com.a5lab.axion.domain.ring.Ring
org.springframework.dao.InvalidDataAccessApiUsageException: detached entity passed to persist: com.a5lab.axion.domain.ring.Ring
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:290)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:163)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218)
	at jdk.proxy4/jdk.proxy4.$Proxy172.save(Unknown Source)

```
